version: "3.7"
services:
  wordpress:
    image: wordpress:latest
    expose:
      - 8000
    env_file: .env
    environment:
      - VIRTUAL_HOST=${WORDPRESS_HOST}
    container_name: wp.wcblocks
    volumes:
      - ./wcblocks:/var/www/html/wp-content/plugins/wcblocks:cached

  next:
    image: node:14
    expose:
      - 3000
    env_file: .env
    environment:
      - VIRTUAL_HOST=${NEXT_HOST}
    container_name: next.wcblocks
    working_dir: /home/node/app
    volumes:
      - ./next-wcb:/home/node/app:cached
    command: ["npm", "run", "dev"]

  vue:
    image: node:14
    expose:
      - 8080
    env_file: .env
    environment:
      - VIRTUAL_HOST=${VUE_HOST}
    container_name: vue.wcblocks
    working_dir: /home/node/app
    volumes:
      - ./vue-wcb:/home/node/app:cached
    command: ["npm", "run", "serve"]

networks:
  default:
    external:
      name: wcblocks
