version: "3.7"
services:
  wordpress:
    image: wordpress:latest
    expose:
      - 8000
    env_file: .env
    environment:
      - VIRTUAL_HOST=${WORDPRESS_HOST}
    container_name: wp.wcblocks
    volumes:
      - ./wcblocks:/var/www/html/wp-content/plugins/wcblocks:cached

networks:
  default:
    external:
      name: wcblocks
