version: "3.7"
services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: nginx.wcblocks
    networks:
      - wcblocks

  db:
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    container_name: db.wcblocks
    networks:
      - wcblocks

  adminer:
    image: adminer
    expose:
      - 8080
    container_name: adminer.wcblocks
    env_file: .env
    environment:
      - VIRTUAL_HOST=${ADMINER_HOST}
    networks:
      - wcblocks

  npm:
    image: verdaccio/verdaccio:4
    expose:
      - 4873
    env_file: .env
    environment:
      - VIRTUAL_HOST=${VERDACCIO_HOST}
    volumes:
      - verdaccio:/verdaccio
    container_name: npm.wcblocks
    networks:
      - wcblocks

volumes:
  db_data:
  verdaccio:

networks:
  wcblocks:
    name: wcblocks
