/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WcbHero {
        "backgroundUrl": string;
        "ctaText": string;
        "heading": string;
    }
}
declare global {
    interface HTMLWcbHeroElement extends Components.WcbHero, HTMLStencilElement {
    }
    var HTMLWcbHeroElement: {
        prototype: HTMLWcbHeroElement;
        new (): HTMLWcbHeroElement;
    };
    interface HTMLElementTagNameMap {
        "wcb-hero": HTMLWcbHeroElement;
    }
}
declare namespace LocalJSX {
    interface WcbHero {
        "backgroundUrl"?: string;
        "ctaText"?: string;
        "heading"?: string;
    }
    interface IntrinsicElements {
        "wcb-hero": WcbHero;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wcb-hero": LocalJSX.WcbHero & JSXBase.HTMLAttributes<HTMLWcbHeroElement>;
        }
    }
}
